### ISSUE TITLE
make sure restartable type waits for canceled instances before being run

### ISSUE THREAD

**Issue by alidcastano** [alidcastano/vuency#12]
There's a bug in the concurrency graph demo that needs to be fixed.

**Comment by machty** [comment]
When would this happen? I've been thinking about this case for e-c, but the only time it'd happen is if a restartable task did a `yield` inside a `finally` hook. Is there another case where this can happen in vuency?

**Comment by alidcastano** [comment]
Honestly, I think this is just a simple oversight on my part, so I mainly created this issue as a reminder. 

If I'm correct, the task is being run and put in a running queue before all the ongoing instances are canceled and removed, so I just need to make sure that the instance waits for all promises inside the array to finish.

**Comment by alidcastano** [comment]
@machty Did you face any troubling cross browser issues when working with e-c?
